In [6]:
import numpy as np 


array = np.array([ 
    [0, 1, 2, 3], 
    [4, 5, 6, 7], 
    [8, 9, 10, 11] 
]) 

print("--- MATRIZ ORIGINAL ---")
print(array)
print("\n")


elemento_5 = array[1, 1]
print(f"1. Elemento '5': {elemento_5}")

segunda_fila = array[1, :]
print(f"2. Segunda fila: {segunda_fila}")

tercera_columna = array[:, 2]
print(f"3. Tercera columna: {tercera_columna}")

columnas_centrales = array[:, 1:3]
print("4. Submatriz columnas centrales:\n", columnas_centrales)
print("\n")

mayores_que_3 = array[array > 3]
print(f"5. Datos mayores que 3: {mayores_que_3}")

datos_pares = array[array % 2 == 0]
print(f"6. Datos pares: {datos_pares}")

--- MATRIZ ORIGINAL ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


1. Elemento '5': 5
2. Segunda fila: [4 5 6 7]
3. Tercera columna: [ 2  6 10]
4. Submatriz columnas centrales:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


5. Datos mayores que 3: [ 4  5  6  7  8  9 10 11]
6. Datos pares: [ 0  2  4  6  8 10]
